DROP DATABASE ibigle_meta;
CREATE DATABASE ibigle_meta;

USE ibigle_meta;

CREATE TABLE TENANT_T(
  TENANT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '租户Id',
  TENANT_CODE VARCHAR(128) NOT NULL COMMENT '租户编码，唯一',
  TENANT_NAME VARCHAR(128) NULL COMMENT '租户名称（中文）',
  TENANT_EN_NAME VARCHAR(128) NULL COMMENT '租户名称（英文）',
  ISOLATION_MODE VARCHAR(20) NULL DEFAULT 'COLUMN' COMMENT '数据隔离模式，SCHEMA 或 COLUMN',
  DB_TYPE TINYINT DEFAULT 1 COMMENT '数据库类型，1->mysql 2->postgresql 3->tidb',
  DB_HOST VARCHAR(256) NULL COMMENT '数据库主机，密文存储IP地址或域名',
  DB_PORT VARCHAR(256) NULL DEFAULT '3306' COMMENT '数据库端口，密文存储，默认为mysql的默认端口3306',
  DB_SCHEMA VARCHAR(128) NULL COMMENT '数据库名称，密文存储',
  DB_USER_NAME VARCHAR(256) NULL COMMENT '数据库登录用户名称，密文存储',
  DB_USER_PASSWORD VARCHAR(256) NULL COMMENT '数据库登录用户密码，密文存储',
  TENANT_STATUS TINYINT NULL DEFAULT 1 COMMENT '租户状态，1->有效 0->无效',
  VALID_FROM VARCHAR(20) NULL COMMENT '租户生效日期，格式：YYYYMMDD->20251110',
  VALID_TO VARCHAR(20) NULL COMMENT '租户失效日期，格式：YYYYMMDD->20251110',
  CREATED_BY VARCHAR(128) NULL COMMENT '创建人',
  CREATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UPDATED_BY VARCHAR(128) NULL COMMENT '最后更新人',
  UPDATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (TENANT_ID),
  UNIQUE KEY UK_TENANT_CODE (TENANT_CODE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE TENANT_T COMMENT = '租户基本信息表';

CREATE TABLE USER_T (
  USER_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户Id',
  TENANT_ID BIGINT NOT NULL COMMENT '租户ID',
  USER_NAME VARCHAR(128) NOT NULL COMMENT '登录用户名，租户内唯一',
  USER_PASSWORD VARCHAR(256) NOT NULL COMMENT '登录密码，密文存储',
  REAL_NAME VARCHAR(128) NULL COMMENT '姓名',
  PHONE_NO VARCHAR(30) NULL COMMENT '电话号码',
  EMAIL VARCHAR(256) DEFAULT NULL COMMENT '邮箱地址',
  USER_STATUS TINYINT DEFAULT 1 COMMENT '用户状态，1->有效 0->无效 2->冻结',
  VALID_FROM VARCHAR(20) NULL COMMENT '租户生效日期，格式：YYYYMMDD->20251110',
  VALID_TO VARCHAR(20) NULL COMMENT '租户失效日期，格式：YYYYMMDD->20251110',
  CREATED_BY VARCHAR(128) NULL COMMENT '创建人',
  CREATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UPDATED_BY VARCHAR(128) NULL COMMENT '最后更新人',
  UPDATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
  LAST_LOGIN_TIME DATETIME DEFAULT NULL COMMENT '最后登录时间',
  LAST_LOGIN_IP VARCHAR(256) DEFAULT NULL COMMENT '最后登录IP',
  PASSWORD_EXPIRE_DT DATE DEFAULT '9999-12-31' COMMENT '密码失效日期（安全要求）', 
  PRIMARY KEY (USER_ID),
  UNIQUE KEY UK_USER_NAME_TENANT (TENANT_ID, USER_NAME),
  KEY IDX_TENANT_ID (TENANT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='用户表';

ALTER TABLE USER_T COMMENT = '用户基础表（支持双模式多租户）';

CREATE TABLE USER_ROLE_REL_T (
  REL_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键Id',
  USER_ID BIGINT NOT NULL COMMENT '用户Id',
  ROLE_ID BIGINT NOT NULL COMMENT '角色Id',
  TENANT_ID BIGINT NOT NULL COMMENT '租户Id',
  PRIMARY KEY (REL_ID),
  UNIQUE KEY (ROLE_ID, USER_ID),
  KEY IDX_USER_ID (USER_ID),
  KEY IDX_TENANT_ID (TENANT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE USER_ROLE_REL_T COMMENT = '用户与角色的关系表（用户拥有的角色定义表）';

CREATE TABLE USER_GROUP_REL_T (
  REL_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键Id',
  GROUP_ID BIGINT NOT NULL COMMENT '用户组Id',
  USER_ID BIGINT NOT NULL COMMENT '用户Id',
  TENANT_ID BIGINT NOT NULL COMMENT '租户Id',
  PRIMARY KEY (REL_ID),
  UNIQUE KEY (GROUP_ID, USER_ID),
  KEY IDX_USER_ID (USER_ID),
  KEY IDX_TENANT_ID (TENANT_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE USER_GROUP_REL_T COMMENT = '用户与用户组的关系表（用户属于用户组）';

CREATE TABLE PERMISSION_DEFINITION_T (
  PERMISSION_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '权限Id',
  PERMISSION_CODE varchar(64) NOT NULL COMMENT '权限码，如 order:view',
  MODULE varchar(64) DEFAULT NULL COMMENT '所属模块',
  PERMISSION_NAME varchar(128) DEFAULT NULL COMMENT '权限名称',
  PERMISSION_DESCRIPTION varchar(256) DEFAULT NULL COMMENT '权限描述',
  SERVICE_NAME varchar(64) DEFAULT NULL COMMENT '微服务名称',
  CLASS_NAME varchar(256) DEFAULT NULL COMMENT '类名称',
  METHOD_NAME varchar(128) DEFAULT NULL COMMENT '方法名称',
  CREATED_BY VARCHAR(128) NULL COMMENT '创建人',
  CREATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UPDATED_BY VARCHAR(128) NULL COMMENT '最后更新人',
  UPDATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (PERMISSION_ID),
  UNIQUE KEY UK_PERMISSION_CODE (PERMISSION_CODE)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE PERMISSION_DEFINITION_T COMMENT = '权限定义表';

CREATE TABLE DIMENSION_DEFINITION_T (
  DIMENSION_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '维度Id',
  DIMENSION_CODE varchar(64) NOT NULL COMMENT '维度编码，如 tenant, dept',
  DIMENSION_NAME varchar(64) DEFAULT NULL COMMENT '维度名称',
  VALUE_TYPE varchar(32) DEFAULT 'STRING' COMMENT '维度值的类型，STRING->字符串, NUMBER->数字, LIST->列表',
  DIMENSION_STATUS TINYINT DEFAULT 1 COMMENT '有效状态，1->有效，0->无效',
  TENANT_ID BIGINT NOT NULL COMMENT '租户Id',
  CREATED_BY VARCHAR(128) NULL COMMENT '创建人',
  CREATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UPDATED_BY VARCHAR(128) NULL COMMENT '最后更新人',
  UPDATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (DIMENSION_ID),
  UNIQUE KEY UK_DIMENSION_CODE (DIMENSION_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE DIMENSION_DEFINITION_T COMMENT = '维度定义表（动态扩展）';

CREATE TABLE AUTHORIZATION_POLICY_T (
  POLICY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '策略Id',
  PRINCIPAL_TYPE varchar(20) NOT NULL COMMENT '对象类型，USER->用户, ROLE->角色, GROUP->用户组',
  PRINCIPAL_ID BIGINT NOT NULL COMMENT '对象主键,用户ID/角色ID/组ID',
  PERMISSION_CODE varchar(64) NOT NULL COMMENT '权限编码',
  DIMENSION_FILTERS json DEFAULT NULL COMMENT '数据维度过滤条件json格式，如{"tenant":["A"],"dept":[100]}',
  POLICY_EFFECT varchar(10) DEFAULT 'ALLOW' COMMENT '策略方向，ALLOW->允许 DENY->拒绝，DENY优先级高于ALLOW',
  VALID_FROM VARCHAR(20) NULL COMMENT '生效日期，格式：YYYYMMDD->20251110',
  VALID_TO VARCHAR(20) NULL COMMENT '失效日期，格式：YYYYMMDD->20251110',
  TENANT_ID BIGINT NOT NULL COMMENT '租户Id',
  CREATED_BY VARCHAR(128) NULL COMMENT '创建人',
  CREATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UPDATED_BY VARCHAR(128) NULL COMMENT '最后更新人',
  UPDATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (POLICY_ID),
  KEY IDX_PRINCIPAL (PRINCIPAL_TYPE, PRINCIPAL_ID),
  KEY IDX_PERMISSION_CODE (PERMISSION_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE AUTHORIZATION_POLICY_T COMMENT = '授权策略表';

CREATE TABLE ROLE_T (
  ROLE_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '策略Id',
  ROLE_NAME varchar(64) NOT NULL COMMENT '角色名称',
  ROLE_CODE varchar(64) NOT NULL COMMENT '角色编码',
  TENANT_ID BIGINT NOT NULL COMMENT '租户Id',
  CREATED_BY VARCHAR(128) NULL COMMENT '创建人',
  CREATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UPDATED_BY VARCHAR(128) NULL COMMENT '最后更新人',
  UPDATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE ROLE_T COMMENT = '角色表';

CREATE TABLE USER_GROUP_T (
  GROUP_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户组Id',
  GROUP_NAME varchar(64) NOT NULL COMMENT '用户组名称',
  TENANT_ID BIGINT NOT NULL COMMENT '租户Id',
  CREATED_BY VARCHAR(128) NULL COMMENT '创建人',
  CREATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UPDATED_BY VARCHAR(128) NULL COMMENT '最后更新人',
  UPDATED_DT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (GROUP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE USER_GROUP_T COMMENT = '用户组定义表';
